import type { LayoutItem, ResponsiveLayouts } from 'react-grid-layout'

/** Stable widget ids — saved layouts depend on these. Never randomize. */
export type DashboardWidgetId =
  | 'active_lanes'
  | 'gdp_compliance'
  | 'temp_deviations'
  | 'high_risk_lanes'
  | 'global_network_map'
  | 'weather_route_alerts'
  | 'corridor_status_table'
  | 'lanes_table'

export const DASHBOARD_WIDGETS: { id: DashboardWidgetId; title: string }[] = [
  { id: 'active_lanes', title: 'Active Lanes' },
  { id: 'gdp_compliance', title: 'GDP Compliant' },
  { id: 'temp_deviations', title: 'Temp Deviations' },
  { id: 'high_risk_lanes', title: 'High Risk Lanes' },
  { id: 'global_network_map', title: 'Global Network Map' },
  { id: 'weather_route_alerts', title: 'Weather & Route Alerts' },
  { id: 'corridor_status_table', title: 'Network Status by Corridor' },
  { id: 'lanes_table', title: 'Active Transport Lanes' },
]

// 12-col grid, rowHeight 48, margin [18,18]. Heights tuned to match the
// current premium layout. Responsive layouts for narrower breakpoints are
// generated by react-grid-layout from `lg`.
const lg: LayoutItem[] = [
  { i: 'active_lanes', x: 0, y: 0, w: 3, h: 3, minW: 2, minH: 3 },
  { i: 'gdp_compliance', x: 3, y: 0, w: 3, h: 3, minW: 2, minH: 3 },
  { i: 'temp_deviations', x: 6, y: 0, w: 3, h: 3, minW: 2, minH: 3 },
  { i: 'high_risk_lanes', x: 9, y: 0, w: 3, h: 3, minW: 2, minH: 3 },
  { i: 'global_network_map', x: 0, y: 3, w: 8, h: 10, minW: 6, minH: 8 },
  { i: 'weather_route_alerts', x: 8, y: 3, w: 4, h: 10, minW: 3, minH: 6 },
  { i: 'corridor_status_table', x: 0, y: 13, w: 12, h: 7, minW: 8, minH: 5 },
  { i: 'lanes_table', x: 0, y: 20, w: 12, h: 9, minW: 8, minH: 6 },
]

export const defaultDashboardLayout: ResponsiveLayouts = { lg }

// lg breakpoint is intentionally low (996) so the dashboard content area
// (≈1100px beside the sidebar) uses the full 12-column layout.
export const GRID_COLS = { lg: 12, md: 8, sm: 4, xs: 2 }
export const GRID_BREAKPOINTS = { lg: 996, md: 768, sm: 480, xs: 0 }
export const GRID_ROW_HEIGHT = 48
export const GRID_MARGIN: [number, number] = [18, 18]

/** Deep clone so callers never mutate the shared default. */
export function cloneDefaultLayout(): ResponsiveLayouts {
  return JSON.parse(JSON.stringify(defaultDashboardLayout))
}
